---
language: node_js
sudo: false
node_js:
  - "8"

install: npm install

before_script:
  - gem install jsduck

script: npx grunt

cache:
  directories:
  - node_modules

branches:
  only:
    - gh-pages
